services:
  all:
    image: alpine
    command: sh -C "echo start"
    depends_on:
      - mongo
      - server

  mongo:
    image: mongo:latest
    container_name: mongo
    env_file: .env
    ports:
      - '${MONGO_PORT}:27017'
    volumes:
      - ./.docker/mongodb/data/db/:/data/db/
      - ./.docker/mongodb/data/log/:/var/log/mongodb/

  server:
    build:
      context: .
      dockerfile: server/Dockerfile
      target: server-dev
    env_file: .env
    volumes:
      - /opt/connect-four-app/node_modules
      - ./server:/opt/connect-four-app/server
      - ./.env:/opt/connect-four-app/.env
      - ./package.json:/opt/connect-four-app/package.json
      - ./yarn.lock:/opt/connect-four-app/yarn.lock
