services:
  mongo:
    image: mongo:latest
    container_name: mongo
    env_file: .env
    ports:
      - '${MONGO_PORT}:27017'
    volumes:
      - ./.docker/mongodb/data/db/:/data/db/
      - ./.docker/mongodb/data/log/:/var/log/mongodb/
